export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { getDoctorAuth } from "@/lib/auth";
import { createModel } from "@/lib/ai/config";
import { prisma } from "@/lib/prisma";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";

const SOAP_SYSTEM_PROMPT = `You are a clinical documentation assistant. Generate a structured SOAP note from the consultation data provided.
Be concise, clinically accurate, and objective. Use standard medical terminology where appropriate.
Output ONLY valid JSON matching the schema — no prose, no markdown fences.`;

const SOAP_NOTE_DISCLAIMER =
  "AI-generated clinical note — review before use. This note was generated by an AI system and must be reviewed by a qualified clinician before being used for any clinical purpose.";

interface SOAPNote {
  disclaimer: string;
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  generatedAt: string;
}

export async function POST(request: NextRequest) {
  const { doctor, error } = await getDoctorAuth();
  if (error) return error;

  if (!doctor!.clinicId) {
    return NextResponse.json(
      { error: "Doctor not assigned to a clinic" },
      { status: 403 },
    );
  }

  let consultationId: string;
  try {
    const body = await request.json();
    consultationId = body.consultationId;
  } catch {
    return NextResponse.json(
      { error: "Invalid request body" },
      { status: 400 },
    );
  }

  if (!consultationId || typeof consultationId !== "string") {
    return NextResponse.json(
      { error: "consultationId is required" },
      { status: 400 },
    );
  }

  const consultation = await prisma.consultation.findUnique({
    where: { id: consultationId },
    select: {
      id: true,
      patientId: true,
      symptoms: true,
      urgencyLevel: true,
      redFlags: true,
      recommendation: true,
      triageResponse: true,
      specialistResponse: true,
      gpResponse: true,
      notes: true,
      patient: { select: { clinicId: true } },
    },
  });

  if (!consultation) {
    return NextResponse.json(
      { error: "Consultation not found" },
      { status: 404 },
    );
  }

  const patientClinicId = consultation.patient.clinicId;
  if (patientClinicId && patientClinicId !== doctor!.clinicId) {
    return NextResponse.json(
      { error: "Consultation not found" },
      { status: 404 },
    );
  }
  if (!patientClinicId) {
    await prisma.patient.update({
      where: { id: consultation.patientId },
      data: { clinicId: doctor!.clinicId },
    });
  }

  const redFlags = (() => {
    try {
      return consultation.redFlags ? JSON.parse(consultation.redFlags) : [];
    } catch {
      return [];
    }
  })();

  const recommendation = consultation.recommendation as Record<
    string,
    unknown
  > | null;
  const differentials =
    recommendation?.differentials ??
    recommendation?.ranked_differentials ??
    null;
  const nextSteps = recommendation?.next_steps ?? recommendation?.plan ?? null;
  const synthesis = recommendation?.synthesis ?? null;

  const consultationContext = `
PATIENT SYMPTOMS: ${consultation.symptoms}
URGENCY LEVEL: ${consultation.urgencyLevel ?? "unknown"}
RED FLAGS IDENTIFIED: ${redFlags.length > 0 ? redFlags.join(", ") : "None"}
TRIAGE RESPONSE: ${consultation.triageResponse ?? "Not available"}
SPECIALIST RESPONSE: ${consultation.specialistResponse ?? "Not available"}
GP RESPONSE: ${consultation.gpResponse ?? "Not available"}
DIFFERENTIAL DIAGNOSES: ${differentials ? JSON.stringify(differentials, null, 2) : "Not available"}
SYNTHESIS / ASSESSMENT: ${synthesis ? String(synthesis) : "Not available"}
NEXT STEPS / PLAN: ${nextSteps ? JSON.stringify(nextSteps, null, 2) : "Not available"}
`.trim();

  const userPrompt = `Based on this consultation data, generate a SOAP note as JSON with this exact structure:
{
  "subjective": "Patient's reported symptoms and history in first-person clinical summary",
  "objective": "Relevant objective findings: urgency level, red flags identified, hypothesis confidence from swarm analysis",
  "assessment": "Ranked differential diagnoses from swarm synthesis with brief rationale",
  "plan": "Recommended next steps, investigations, and follow-up plan"
}

Consultation data:
${consultationContext}`;

  try {
    const model = createModel(0.2);
    const response = await model.invoke([
      new SystemMessage(SOAP_SYSTEM_PROMPT),
      new HumanMessage(userPrompt),
    ]);

    const rawContent =
      typeof response.content === "string"
        ? response.content
        : JSON.stringify(response.content);

    const jsonMatch = rawContent.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error(
        "SOAP generation: no JSON found in LLM response",
        rawContent,
      );
      return NextResponse.json(
        { error: "Failed to parse generated note" },
        { status: 500 },
      );
    }

    const parsed = JSON.parse(jsonMatch[0]) as {
      subjective?: string;
      objective?: string;
      assessment?: string;
      plan?: string;
    };

    const note: SOAPNote = {
      disclaimer: SOAP_NOTE_DISCLAIMER,
      subjective: parsed.subjective ?? "",
      objective: parsed.objective ?? "",
      assessment: parsed.assessment ?? "",
      plan: parsed.plan ?? "",
      generatedAt: new Date().toISOString(),
    };

    await prisma.consultation.update({
      where: { id: consultationId },
      data: { notes: note as unknown as Record<string, string> },
    });

    return NextResponse.json({ note });
  } catch (err) {
    console.error("SOAP note generation error:", err);
    return NextResponse.json(
      { error: "Failed to generate clinical note" },
      { status: 500 },
    );
  }
}
